apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alexa-digital-mongo-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: alexa-digital-mongo 
    spec:
      containers:
      - name: alexa-digital-mongo 
        image: digital/alexa_digital_mongo:latest
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: alexa-digital-mongo-svc
spec:
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
  type: NodePort 
  selector:
    k8s-app: alexa-digital-mongo 
